version: 2

sources:
  - name: staging
    database: marine-tensor-448017-p9
    schema: de_zoomcamp
      # loaded_at_field: record_loaded_at
    tables:
      - name: green_tripdata
      - name: yellow_tripdata